# Generated by Django 3.2.9 on 2021-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
