# Generated by Django 3.2.9 on 2021-12-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto_App', '0003_dish_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Cooking_Time',
            field=models.CharField(max_length=40),
        ),
    ]
