# Generated by Django 3.2.9 on 2021-12-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto_App', '0004_alter_dish_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='Resto_App.district'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='Resto_App.sector'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish', to='Resto_App.restaurant'),
        ),
    ]
